version: '3'

services:
  beerus-rpc:
    image: "beerus:${BEERUS_VERSION:-latest}"
    ports:
      - '3030:3030'
      - '3031:3031'
    environment:
      ETHEREUM_NETWORK: "${ETHEREUM_NETWORK:-mainnet}"
      ETHEREUM_CONSENSUS_RPC_URL: "${ETHEREUM_CONSENSUS_RPC_URL}"
      ETHEREUM_EXECUTION_RPC_URL: "${ETHEREUM_EXECUTION_RPC_URL}"
      STARKNET_RPC_URL: "${STARKNET_RPC_URL}"
