name: continuous integration

on:
  pull_request:

env:
  BEERUS_VERSION: ci
  ETHEREUM_NETWORK: mainnet
  ETHEREUM_CONSENSUS_RPC_URL: ${{ secrets.ETHEREUM_CONSENSUS_RPC_URL }}
  ETHEREUM_EXECUTION_RPC_URL: ${{ secrets.ETHEREUM_EXECUTION_RPC_URL }}
  STARKNET_RPC_URL: ${{ secrets.STARKNET_RPC_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and export
        uses: docker/build-push-action@v2
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: beerus:${{ env.BEERUS_VERSION }}
          outputs: type=docker,dest=/tmp/beerus.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: beerus
          path: /tmp/beerus.tar

  e2e-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: beerus
          path: /tmp
      - name: Load docker image
        run: |
          docker load --input /tmp/beerus.tar
          docker image ls -a
      - name: execute the rpc in background
        run: |
          docker compose up -d 
          hurl --retry --retry-max-count 60 ./examples/beerus-rpc/starknet/starknet_blockNumber.hurl > /dev/null;
      - name: print the docker logs
        run: docker compose logs
